Add Expense entities
kenez92/Auto-Manager pull request #12
Opened 2021-01-20 21:10 UTC by tomekmiernik

2021-01-20 21:20 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +    Collection<Vulcanization> vulcanization;
W tej adnotacji brakuje fetcha, targetEntity oraz cascady.
Nie lepiej zamiast Collection użyć Listy ? :)

2021-01-20 21:21 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +        }
Przy polach klasy możesz ustawić inicjalizację pola. Czemu HashSet ?

2021-01-20 21:23 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +@MappedSuperclass
Nie jestem przekonany czy używanie @MappedSuperClass to najlepsza praktyka. Mam nadzieję, że nasz mentor nam odpowie na to pytanie :D

2021-01-20 21:26 UTC, kenez92 reviewed
Ogólnie z tego co widzę to sobie bardzo życie utrudniłeś. Ja bym utworzył do tego po prostu encje z polami takimi jakimi potrzebujemy

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +@MappedSuperclass
Ogolnie dziedziczenie nie jest za dobre wiec unikalbym takich konstrukcji.

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +        }
Set w przypadku takich relacji moze byc w wielu rzypadkach duzo lepsze niz Lista wiec nie jest zle

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +    private Long expenseId;
Tu wystarczy po prostu id. Wiadomo po klasie ze chodzi o expense

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +    private String uuid = UUID.randomUUID().toString();
Tu moze byc po prostu UUID jako typ

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Insurance.java
> +@Builder
Jak masz tu Buildera to Twoje UUID z BaseEntity bedzie chyba nadpisane. Trzeba sprawdzic ale lepiej buildera robic na konstruktorze w ktorym nie bedzie UUID

2021-01-20 22:21 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +public class Expense {
Zastanawiam sie czy te wszystkie dodatkowe encje sa potrzebne. Mozna to zrobic na encji Expense i wstawic typ oznaczajace jaki to wydatek. Dodatkowe pola mozna zrobic jako kolumna typu JSON i trzymac luzne dane. Nie wiem czy to nie byloby prostrze i szybsze bo bedzie mniej JOINow przy wyciaganiu danych.

2021-01-21 16:16 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +        }
@kenez92 zgadza się jednak pod uwagę brałem w tym przypadku odsunięcie tej czynności do momentu dodawania kosztu. Nie wszystkie koszty będą wprowadzane w tym samym czasie. Niektóre z nich user doda dopiero jak ubezpieczy samochód lub złapie kapcia, wtedy to kolekcja zostanie powołana do życia.

2021-01-21 16:20 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +@MappedSuperclass
oczywiście zgadzam się z Wami, ale czy w przypadku tak małej klasy też może się okazać bardzo problematyczna? Oszczędza to trochę linii kodu w pozostałych klasach. Czy wstawienie BaseExpense jako pola do tych klas coś zmieni na lepsze?

2021-01-21 16:21 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +    private Long expenseId;
ok, zmienimy,

2021-01-21 16:24 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +    private String uuid = UUID.randomUUID().toString();
ok, nie wiedziałem, co sądzisz w ogóle o takim oznaczaniu obiektów? Ma to sens? Ja się z tym spotkałem w jednym z tutoriali, strasznie gościu zachwalał takie podejście. Osobiście nie miałem okazji pracowania przy jakiś znaczących projektach. To popularna praktyka?

2021-01-21 16:28 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +public class Expense {
szczerze mówiąc też mi się to średnio widzi, ale jak dobrze zrozumiałem @kenez92 tego oczekiwał. Jedna klasa Expense i w pola z wydatkami, ale...w takim razie, pola muszą być kolekcjami. No chyba, że jest inaczej, to proszę o naprostowanie mojego myślenia

2021-01-21 16:28 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +    Collection<Vulcanization> vulcanization;
ok, poprawimy

2021-01-21 16:42 UTC, tomekmiernik commented
_@kenez92
Ogólnie z tego co widzę to sobie bardzo życie utrudniłeś. Ja bym utworzył do tego po prostu encje z polami takimi jakimi potrzebujemy_

co masz na myśli utworzył encje z polami?? W sensie w klasie Expense podklasy? Napisz proszę, albo podrzuć schemat tak będzie prościej. Wydawało mi się, że tak to opisywałeś, Car <-> Expense (relacja jeden do jeden) i w klasie Expense pola opisujące wydatki w relacji np. Expnse <=> Insurance (relacja jeden do wielu), jak do wielu to rozumiem, że jakaś kolekcja.

2021-01-21 16:45 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Insurance.java
> +@Builder
co proponujesz?

2021-01-21 17:22 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +public class Expense {
Kazdy z tych specyficznych wydatkow to bedzie osobny wiersz w tabeli expense. Po typie rozpoznasz jaki to wydatek. Wspolne pola beda w kolumnach a dodatkowe specyficzne pola mozna zapakowac w jsona albo zrobic dodatkowe kolumny ale wtedy masz redundantne kolumny

2021-01-21 17:23 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Insurance.java
> +@Builder
Jak nie bedziesz mial dziedziczenia to stworz sobie konstruktor z wszystkimi polami oprocz uuid i na konstruktorze daj adnotacje Builder

2021-01-21 17:27 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +    private String uuid = UUID.randomUUID().toString();
Ogolnie uuid dobrze uzywac do identyfikacji na froncie bo nikt nie zgadnie kolejnego id i wtedy jest mniejsze pole do zrobienia ataku czy zwyklego podebrania danych gdy security jest slabe. Do kluczy glownych bym nie uzywal bo to jednal spora wartosc i musisz przy kazdej relacji ja umieszczac jako klucz obcy wiec bez sensu troche tyle pamieci wykorzystywac. Do dodatkowej jednoznacznej identyfikacji super. No i mozesz tez uzywac tej wartosci w equals i hashCode. Wtedy bedzie szybciej bo nie jest wyliczane w locie na podstawie danych czyli masz cos w rodzaju niezmiennika.

2021-01-21 17:28 UTC, michalcholewinski commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +@MappedSuperclass
Przy skomplikowanych zmianach moga sie pojawic problemy woec lepiej skopiowac pola albo zrobic Embedable class

2021-01-21 20:42 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +public class Expense {
Mój zamysł był zrobienie głównej encji Expanse i stopniowo dodawać kolejne encje OneToOne do każdego wydatku. W ten sposób możemy łatwo skalować aplikację, a nie zamykać się w całej aplikacji do 3 encji. No ale jak chcecie to możemy zrobić to w ten sposób, żeby była jedna encja Expanse i typ wyliczeniowy, który będzie określał typ wydatku.

2021-01-21 20:47 UTC, kenez92 commented
> _@kenez92 Ogólnie z tego co widzę to sobie bardzo życie utrudniłeś. Ja bym utworzył do tego po prostu encje z polami takimi jakimi potrzebujemy_
> 
> co masz na myśli utworzył encje z polami?? W sensie w klasie Expense podklasy? Napisz proszę, albo podrzuć schemat tak będzie prościej. Wydawało mi się, że tak to opisywałeś, Car <-> Expense (relacja jeden do jeden) i w klasie Expense pola opisujące wydatki w relacji np. Expnse <=> Insurance (relacja jeden do wielu), jak do wielu to rozumiem, że jakaś kolekcja.

Chciałem, żebyś utworzył encje Expanse, a w kolejnych zadaniach byśmy po prostu rozszerzali o kolejne encje w razie potrzeby :) No i jeżeli o mnie chodzi to na pewno bym nie użył dziedziczenia przy tworzeniu tabel. Prędzej @Embeddable ;)

2021-01-22 15:16 UTC, tomekmiernik commented
> 
> 
> > _@kenez92 Ogólnie z tego co widzę to sobie bardzo życie utrudniłeś. Ja bym utworzył do tego po prostu encje z polami takimi jakimi potrzebujemy_
> > co masz na myśli utworzył encje z polami?? W sensie w klasie Expense podklasy? Napisz proszę, albo podrzuć schemat tak będzie prościej. Wydawało mi się, że tak to opisywałeś, Car <-> Expense (relacja jeden do jeden) i w klasie Expense pola opisujące wydatki w relacji np. Expnse <=> Insurance (relacja jeden do wielu), jak do wielu to rozumiem, że jakaś kolekcja.
> 
> Chciałem, żebyś utworzył encje Expanse, a w kolejnych zadaniach byśmy po prostu rozszerzali o kolejne encje w razie potrzeby :) No i jeżeli o mnie chodzi to na pewno bym nie użył dziedziczenia przy tworzeniu tabel. Prędzej @Embeddable ;)

ok, czyli bazową klasą jest Expense, którą będziemy rozszerzać klasami Insurance, Repait itd. Do rozszerzenia tej klasy użyjemy jak rozumiem Kompozycji i adnotacji @Embeddable. Jeśli dobrze zrozumiałem koncepcję, to żeby było co testować, utworzę dla testów klasę/encję Repair. 

Zastanawiam się jeszcze jak powiązać te wydatki z autem. W klasie Car będzie pole typu Expense?? Czy Collection<Expense>? Tych wydatków "jednego typu" trochę będzie, np. Tankowanie. Gdzieś musi się pojawić jakaś kolekcja, lista zbiór.

2021-01-23 11:58 UTC, kenez92 commented
> > > _@kenez92 Ogólnie z tego co widzę to sobie bardzo życie utrudniłeś. Ja bym utworzył do tego po prostu encje z polami takimi jakimi potrzebujemy_
> > > co masz na myśli utworzył encje z polami?? W sensie w klasie Expense podklasy? Napisz proszę, albo podrzuć schemat tak będzie prościej. Wydawało mi się, że tak to opisywałeś, Car <-> Expense (relacja jeden do jeden) i w klasie Expense pola opisujące wydatki w relacji np. Expnse <=> Insurance (relacja jeden do wielu), jak do wielu to rozumiem, że jakaś kolekcja.
> > 
> > 
> > Chciałem, żebyś utworzył encje Expanse, a w kolejnych zadaniach byśmy po prostu rozszerzali o kolejne encje w razie potrzeby :) No i jeżeli o mnie chodzi to na pewno bym nie użył dziedziczenia przy tworzeniu tabel. Prędzej @Embeddable ;)
> 
> ok, czyli bazową klasą jest Expense, którą będziemy rozszerzać klasami Insurance, Repait itd. Do rozszerzenia tej klasy użyjemy jak rozumiem Kompozycji i adnotacji @Embeddable. Jeśli dobrze zrozumiałem koncepcję, to żeby było co testować, utworzę dla testów klasę/encję Repair.
> 
> Zastanawiam się jeszcze jak powiązać te wydatki z autem. W klasie Car będzie pole typu Expense?? Czy Collection? Tych wydatków "jednego typu" trochę będzie, np. Tankowanie. Gdzieś musi się pojawić jakaś kolekcja, lista zbiór.

Jak dla mnie najlepszym pomysłem byłoby utworzyć klasę Expanse z podstawowymi informacjami takimi jak - Data wystąpienia, Koszt wydatku. Klasa car powinna mieć pole Expanse, która byłaby w relacji 1 do 1 z samochodem. Z czasem rozrostu aplikacji moglibyśmy dodać kolejne Encje. Expanse byłaby w relacji z nowymi wydatkami OneToMany czyli expanse miałaby kolekcje np ubezpieczenia Oc. Moglibyśmy zrobić na repozytorium zapytanie @Query, aby uniknąć problemu hibernate N+1. Na chwilę obecną wystarczyłaby nam podstawowa Encja expanse i przykładowa RandomExpanse.

2021-01-24 19:06 UTC, tomekmiernik commented
ok, naniosłem zmiany, dajcie znać czy jest ok.

2021-01-25 14:33 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/expanses/BaseExpanse.java
> +    private String uuid = UUID.randomUUID().toString();
poprawiłem

2021-01-25 14:33 UTC, tomekmiernik commented on src/main/java/pl/car/automanager/persistence/entity/Expense.java
> +    private Long expenseId;
poprawiłem

2021-01-25 20:58 UTC, kenez92 commented
> ok, naniosłem zmiany, dajcie znać czy jest ok.

W Twojej implementacji wstrzykujesz kolumny z encji Repair do Expanse. W przypadku dodania kolejnych encji będziemy mieli milion pustych kolumn w jednej encji. Powinno być odwrotnie :) Chyba, że się mylę ?

Co myślisz o takiej prostej implementacji ? 

public class Repair {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    // dodatkowe pola, u jakjiego mechanika co za naprawa itd itp
    @ManyToOne
    private Expense expense;
}

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID")
    private Long id;

    @Column(name = "DATE")
    private LocalDate date;

    @Column(name = "COST", nullable = false)
    private BigDecimal cost;

    @OneToMany(
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL,
            mappedBy = "expanse",
            targetEntity = Repair.class)
    private List<Repair> repair = new ArrayList<>();
    
    W tym przypadku możemy sobie spokojnie skalować o kolejne wydatki bez zbędnych kolumn

2021-01-27 08:59 UTC, tomekmiernik commented
> 
> 
> > ok, naniosłem zmiany, dajcie znać czy jest ok.
> 
> W Twojej implementacji wstrzykujesz kolumny z encji Repair do Expanse. W przypadku dodania kolejnych encji będziemy mieli milion pustych kolumn w jednej encji. Powinno być odwrotnie :) Chyba, że się mylę ?
> 
> Co myślisz o takiej prostej implementacji ?
> 
> public class Repair {
> @id
> @GeneratedValue(strategy = GenerationType.AUTO)
> private Long id;
> // dodatkowe pola, u jakjiego mechanika co za naprawa itd itp
> @manytoone
> private Expense expense;
> }
> 
> ```
> @Id
> @GeneratedValue(strategy = GenerationType.AUTO)
> @Column(name = "ID")
> private Long id;
> 
> @Column(name = "DATE")
> private LocalDate date;
> 
> @Column(name = "COST", nullable = false)
> private BigDecimal cost;
> 
> @OneToMany(
>         fetch = FetchType.EAGER,
>         cascade = CascadeType.ALL,
>         mappedBy = "expanse",
>         targetEntity = Repair.class)
> private List<Repair> repair = new ArrayList<>();
> ```
> 
> W tym przypadku możemy sobie spokojnie skalować o kolejne wydatki bez zbędnych kolumn

poprawione

2021-01-27 22:26 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Insurance.java
> +/*
Zakomentowanego kodu nie commitujemy :)

2021-01-27 22:26 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Refueling.java
> +/*
Zakomentowanego kodu nie commitujemy :)

2021-01-27 22:26 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Registration.java
> +/*
Zakomentowanego kodu nie commitujemy :)

2021-01-27 22:27 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Service.java
> +/*
Zakomentowanego kodu nie commitujemy :)

2021-01-27 22:27 UTC, kenez92 commented on src/main/java/pl/car/automanager/persistence/entity/expanses/Vulcanization.java
> +/*
Zakomentowanego kodu nie commitujemy :)

2021-01-27 22:28 UTC, kenez92 commented on src/test/java/pl/car/automanager/persistence/entity/CarTestSuite.java
> +    @Test
Testy powinny być w deydkowanej klasie dla odpowiedniej encji

2021-01-27 22:28 UTC, kenez92 requested changes
Zakomentowanego kodu nie commitujemy :) Więc albo usuń zbędny kod albo zrób go tak jak być powinien z dedykowanymi dla niego klasami testowymi :)

2021-01-31 16:00 UTC, tomekmiernik commented
> 
> 
> Zakomentowanego kodu nie commitujemy :) Więc albo usuń zbędny kod albo zrób go tak jak być powinien z dedykowanymi dla niego klasami testowymi :)

poprawiłem

2021-02-02 15:19 UTC, kenez92 approved these changes
Jedynie mogę się do tego doczepić : 
@LazyCollection(LazyCollectionOption.FALSE)

jest to równoznaczne z fetchType = EAGER. Co jest lepiej czytelne. Chyba, że się mylę ? :)

2021-02-09 22:15 UTC, MichalMazurek11 approved these changes

2021-02-22 15:09 UTC, tomekmiernik commented
zmieniłem adnotacje @LazyCollection.

2021-02-23 14:56 UTC, merged